import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
    const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://cvber.vercel.app'

    return {
        rules: [
            {
                userAgent: '*',
                allow: '/',
                disallow: ['/api/', '/dashboard'],
            },
            // Explicitly allow AI crawlers for GEO/AEO
            {
                userAgent: [
                    'GPTBot',
                    'ChatGPT-User',
                    'Google-Extended',
                    'Googlebot',
                    'BingBot',
                    'Bingbot',
                    'BingPreview',
                    'PerplexityBot',
                    'YouBot',
                    'ClaudeBot',
                    'Claude-Web',
                    'anthropic-ai',
                    'cohere-ai',
                    'meta-externalagent',
                    'meta-externalfetch',
                    'Applebot-Extended',
                    'Bytespider',
                    'Amazonbot',
                    'YandexBot',
                    'DuckDuckBot',
                    'Slurp',
                    'Sogou',
                    'facebot',
                    'Pinterestbot',
                    'Slackbot',
                    'TelegramBot',
                    'WhatsApp',
                    'Twitterbot',
                    'LinkedInBot',
                    'Redditbot',
                ],
                allow: [
                    '/',
                    '/features',
                    '/how-it-works',
                    '/art-hub',
                    '/verify',
                    '/what-is-cvber',
                    '/best-art-protection-tool',
                    '/cvber-vs-glaze',
                    '/c2pa-certificate',
                    '/dmca-takedown',
                    '/ai-art-theft',
                    '/how-to-stop-ai-training-on-my-art',
                    '/copyright-protection-instagram',
                    '/copyright-protection-youtube',
                    '/copyright-protection-tiktok',
                    '/copyright-protection-deviantart',
                    '/copyright-protection-reddit',
                    '/copyright-protection-pinterest',
                    '/blog',
                    '/blog/how-to-protect-art-from-ai',
                    '/blog/c2pa-explained',
                    '/blog/dmca-guide-for-artists',
                    '/blog/glaze-vs-nightshade',
                    '/blog/best-free-art-protection-tools',
                    '/blog/ai-training-opt-out',
                    '/blog/copyright-protection-for-photographers',
                    '/blog/nft-art-protection',
                    '/llms.txt',
                    '/llms-full.txt',
                ],
                disallow: ['/api/', '/dashboard'],
            },
        ],
        sitemap: `${baseUrl}/sitemap.xml`,
    }
}
