import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
    const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://cvber.vercel.app'

    return {
        rules: [
            {
                userAgent: '*',
                allow: '/',
                disallow: ['/api/', '/dashboard', '/login', '/register', '/onboarding', '/demo', '/ping', '/gate', '/claim'],
            },
            // Explicitly allow AI crawlers for GEO/AEO
            {
                userAgent: [
                    'GPTBot',
                    'ChatGPT-User',
                    'Google-Extended',
                    'Googlebot',
                    'BingBot',
                    'Bingbot',
                    'BingPreview',
                    'PerplexityBot',
                    'YouBot',
                    'ClaudeBot',
                    'Claude-Web',
                    'anthropic-ai',
                    'cohere-ai',
                    'meta-externalagent',
                    'meta-externalfetch',
                    'Applebot-Extended',
                    'Bytespider',
                    'Amazonbot',
                    'YandexBot',
                    'DuckDuckBot',
                    'Slurp',
                    'Sogou',
                    'facebot',
                    'Pinterestbot',
                    'Slackbot',
                    'TelegramBot',
                    'WhatsApp',
                    'Twitterbot',
                    'LinkedInBot',
                    'Redditbot',
                    'Omgilibot',
                    'FriendlyCrawler',
                    'Timpibot',
                    'Velenbot',
                    'webzio',
                    'semrush',
                    'DotBot',
                    'MJ12bot',
                    'AhrefsBot',
                    'DataForSeoBot',
                ],
                allow: [
                    '/',
                    '/features',
                    '/how-it-works',
                    '/art-hub',
                    '/verify',
                    '/about',
                    '/what-is-cvber',
                    '/best-art-protection-tool',
                    '/cvber-vs-glaze',
                    '/c2pa-certificate',
                    '/dmca-takedown',
                    '/ai-art-theft',
                    '/how-to-opt-out-of-ai-training',
                    '/copyright-protection-instagram',
                    '/copyright-protection-youtube',
                    '/copyright-protection-tiktok',
                    '/copyright-protection-deviantart',
                    '/copyright-protection-reddit',
                    '/copyright-protection-pinterest',
                    '/blog',
                    '/blog/how-to-protect-art-from-ai',
                    '/blog/c2pa-explained',
                    '/blog/dmca-guide-for-artists',
                    '/blog/glaze-vs-nightshade',
                    '/blog/best-free-art-protection-tools',
                    '/blog/ai-training-opt-out',
                    '/blog/copyright-protection-for-photographers',
                    '/blog/nft-art-protection',
                    '/blog/can-ai-steal-your-art',
                    '/blog/is-my-art-being-used-to-train-ai',
                    '/blog/best-art-protection-software',
                    '/blog/verify-artwork-ownership',
                    '/blog/art-protection-tools-comparison',
                    '/blog/tools-for-copyrighting-art',
                    '/blog/easiest-way-to-protect-digital-art',
                    '/cvber-vs-nightshade',
                    '/cvber-vs-pixsy',
                    '/cvber-vs-digimarc',
                    '/is-cvber-legit',
                    '/how-to-protect-your-art',
                    '/free-guide',
                    '/llms.txt',
                    '/llms-full.txt',
                    '/sitemap.xml',
                ],
                disallow: ['/api/', '/dashboard'],
            },
        ],
        sitemap: `${baseUrl}/sitemap.xml`,
    }
}
