services:
  - type: web
    name: cvber-backend
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    plan: free
    region: ohio
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GROQ_API_KEY
        value: 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
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: C2PA_SERVICE_URL
        fromService:
            name: cvber-c2pa
            type: web
            property: host

  - type: web
    name: cvber-c2pa
    env: docker
    dockerContext: c2pa-service
    dockerfilePath: Dockerfile
    plan: free
    region: ohio
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
