services:
  - type: web
    name: cvber-backend
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    plan: free
    region: ohio
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: SUPABASE_URL
        value: "https://fklluemyardnjwcqrzgw.supabase.co"
      - key: SUPABASE_ANON_KEY
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrbGx1ZW15YXJkbmp3Y3Fyemd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcxODY3NDYsImV4cCI6MjA4Mjc2Mjc0Nn0.DWwedN58Reit3MG4hIniKquOVzsbeV0Nr63n7Dr0NQ0"
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "https://cvber.free.las.app,https://cvber.vercel.app"
      - key: NVIDIA_NIM_API_KEY
        sync: false
      - key: C2PA_SERVICE_URL
        fromService:
            name: cvber-c2pa
            type: web
            property: host
