// DEPRECATED: this generates a demo document only. do not use for legal purposes.
// real C2PA certificates are generated by the backend C2PA service.

import jsPDF from 'jspdf';

interface AffidavitData {
    fileName: string;
    fileSize?: number;
    originalityScore: number;
    aiProvider: string;
    aiModel: string;
    forensicSummary: string;
    timestamp: string;
}

export const generateLegalAffidavit = (data: AffidavitData) => {
    const doc = new jsPDF();

    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(0, 0, 0);
    doc.text("CVBER PROTECTION RECEIPT", 105, 20, { align: "center" });

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("This is a demo receipt, not a legal document.", 105, 28, { align: "center" });
    doc.text("Real C2PA certificates are generated by the CVBER backend service.", 105, 34, { align: "center" });

    doc.setLineWidth(0.5);
    doc.line(20, 40, 190, 40);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("FILE INFORMATION", 20, 55);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`File Name: ${data.fileName}`, 25, 65);
    doc.text(`File Size: ${data.fileSize ? (data.fileSize / 1024).toFixed(2) + ' KB' : 'Unknown'}`, 25, 72);
    doc.text(`Timestamp: ${data.timestamp}`, 25, 79);
    doc.text("Hash verification requires backend C2PA service integration", 25, 86);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("SCAN RESULTS", 20, 105);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Originality Score: ${data.originalityScore.toFixed(1)}/100`, 25, 115);
    doc.text(`AI Engine: ${data.aiProvider} (${data.aiModel})`, 25, 122);

    const splitSummary = doc.splitTextToSize(`Finding: ${data.forensicSummary}`, 170);
    doc.text(splitSummary, 25, 132);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("DEMO RECEIPT", 20, 165);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const disclaimerText = `This document is a scan receipt generated by CVBER for demonstration purposes only. It does not constitute legal proof of ownership or copyright. For legally admissible C2PA certificates, use the CVBER platform to generate certificates through the backend C2PA service.`;
    const splitDisclaimer = doc.splitTextToSize(disclaimerText, 170);
    doc.text(splitDisclaimer, 25, 175);

    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by CVBER | Demo Receipt | Not a Legal Document", 105, 280, { align: "center" });

    doc.save(`CVBER_Receipt_${data.fileName.replace(/\s+/g, '_')}.pdf`);
};
